name: electron

on:
    push:
        tags:
            - 'v*.*.*'

jobs:
    release:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v1

            - name: Install Node.js
              uses: actions/setup-node@v3.0.0
              with:
                  node-version: '16'

            - name: Install Dependencies
              run: yarn install

            - name: build-linux
              if: matrix.os == 'ubuntu-latest'
              uses: actions/setup-node@v3.0.0
              with:
                  node-version: '16'
                  GH_TOKEN: ${{ secrets.github_token }}
              run: yarn run binary:build:linux

            - name: build-mac
              if: matrix.os == 'macos-latest'
              with:
                  node-version: '16'
                  GH_TOKEN: ${{ secrets.github_token }}
              run: yarn run binary:build:mac

            - name: build-win
              if: matrix.os == 'windows-latest'
              with:
                  node-version: '16'
                  GH_TOKEN: ${{ secrets.github_token }}
              run: yarn run binary:build:win

            - name: release
              uses: softprops/action-gh-release@v1
              with:
                  draft: true
                  files: |
                      dist/*.exe
                      dist/*.zip
                      dist/*.dmg
                      dist/*.AppImage
                      dist/*.snap
                      dist/*.deb
                      dist/*.rpm
                      dist/*.tar.gz
              env:
                  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
